# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: jgamblin/kalibrowser
# Ports to expose on workspace startup (optional)
ports:
  - port: 6080
    onOpen: open-preview
