# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: jupyter/datascience-notebook
# Ports to expose on workspace startup (optional)
ports:
  - port: 8888
    onOpen: open-preview
